### ISSUE TITLE
ENH: Linked Data Platform API (RDF (Turtle), JSON-LD)

### ISSUE THREAD

**Issue by westurner** [jeffknupp/sandman#94]
LDP http://www.w3.org/TR/ldp/ is a RESTful API for Linked Data. It would be great to generate the API controllers along with sandman's SQLAlchemy introspection and configuration configuration. (... d2rq provides a different sort of capability).

**Background**
- http://www.w3.org/TR/ldp/
- Paging: http://www.w3.org/TR/ldp-paging/#ldpp-ex-mx
- Test Suite: https://dvcs.w3.org/hg/ldpwg/raw-file/default/tests/ldp-testsuite.html
- Test Suite: https://w3c.github.io/ldp-testsuite/

**_content-types**_
- https://en.wikipedia.org/wiki/Turtle_(syntax)
  - https://rdflib.readthedocs.org/en/latest/intro_to_creating_rdf.html
  - rdfpipe
- https://en.wikipedia.org/wiki/JSON-LD
  - http://json-ld.org/#developers
  - http://json-ld.org/test-suite/
  - https://github.com/digitalbazaar/pyld

**Tasks**
- [ ] LDPResource
- [ ] LDPContainer
- [ ] JSON-LD context
- [ ] JSON-LD serializer (pyld, rdflib-jsonld)
- [ ] TTL serializer (rdflib)

**Value**
- http://5stardata.info/
- http://www.w3.org/community/rdfjs/wiki/Comparison_of_RDFJS_libraries

**Comment by westurner** [comment]
... http://www.w3.org/TR/ldp-paging/#ldpp-ex-mx
